<?php

/**
 * @file
 * Example module for Panopoly Confg.
 */

/**
 * Implements hook_panopoly_config_info()
 */
function panopoly_config_example_panopoly_config_info() {
  $info = array();

  // General
  $info['general'] = array(
    'title' => t('General'),
    'description' => t('General settings such as site name, site mail.'),
    'weight' => 10,
    'config' => array(
      'site_name' => array(
        'title' => t('Site name'),
        'type' => 'string',
        'default' => variable_get('site_name', 'Drupal'),
      ),
      'site_mail' => array(
        'title' => t('Site mail'),
        'type' => 'string',
        'default' => variable_get('site_mail'),
      ),
    ),
  );

  // Services.
  $info['services'] = array(
    'title' => t('Services'),
    'description' => t('Settings for external web services such as Google analytics, Disqus..etc'),
    'weight' => 30,
    'config' => array(
      'googleanalytics_account' => array(
        'title' => t('Google analytics ID'),
        'description' => t('Google analytics ID in the form of UA-xxxxxxx-yy. !link for advanced settings.', array(
          '!link' => l(t('Click here'), 'admin/config/system/googleanalytics'),
        )),
        'type' => 'string',
      ),
    ),
  );

  return $info;
}
